name: Build Catalyst Wheel on macOS (x86_64)

on:
  workflow_dispatch:
  workflow_call:

env:
  MACOSX_DEPLOYMENT_TARGET: 12

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_if_wheel_build_required:
    uses: ./.github/workflows/check-for-wheel-build.yml

  constants:
    needs: [check_if_wheel_build_required]
    if: needs.check_if_wheel_build_required.outputs.build-wheels == 'true'
    name: "Set build matrix"
    uses: ./.github/workflows/constants.yaml

  build-dependencies:
    needs: [constants, check_if_wheel_build_required]

    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        arch: [x86_64]
        python_version: [3.9]

    name: Build Dependencies (Python ${{ matrix.python_version }})
    runs-on: macos-12

    if: needs.check_if_wheel_build_required.outputs.build-wheels == 'true'

    steps:
    - name: Checkout Catalyst repo
      uses: actions/checkout@v4

  catalyst-macos-wheels-x86-64:
    needs: [constants, build-dependencies]
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        arch: [x86_64]
        python_version: ${{ fromJson(needs.constants.outputs.python_versions) }}

    name: Build Wheels (Python ${{ matrix.python_version }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Repair wheel using delocate-wheel
      run: |
        mkdir wheel
        touch wheel/PennyLane_Catalyst-0.8.0.dev0-cp${{ matrix.python_version }}-cp${{ matrix.python_version }}-macosx_12_0_x86_64.whl

    - name: Upload Wheel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: catalyst-macos_x86_64-wheel-py-${{ matrix.python_version }}.zip
        path: wheel/
        retention-days: 14
